services:
  - type: web
    name: alumni-backend
    runtime: docker  # This tells Render to look for your Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "*"
    buildCommand: |
      # 1. Update pip and force install setuptools into the environment
      pip install --upgrade pip setuptools wheel
      
      # 2. Install the SQL Driver
      curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
      curl https://packages.microsoft.com/config/debian/11/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
      sudo apt-get update
      sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
      
      # 3. Install requirements (including the new simplejwt)
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn alumni_system.wsgi:application