# Generated by Django 4.2.29 on 2026-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnidetails',
            fields=[
                ('alumniid', models.AutoField(db_column='AlumniID', primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, db_column='RegistrationNumber', max_length=50, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('graduationyear', models.IntegerField(blank=True, db_column='GraduationYear', null=True)),
                ('degree', models.CharField(blank=True, db_column='Degree', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('chapterid', models.IntegerField(blank=True, db_column='ChapterID', null=True)),
                ('isverified', models.BooleanField(blank=True, db_column='IsVerified', default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni Details',
                'db_table': 'AlumniDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumniprograms',
            fields=[
                ('programid', models.AutoField(db_column='ProgramID', primary_key=True, serialize=False)),
                ('programname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProgramName', max_length=100, null=True)),
                ('programtype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProgramType', max_length=50, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni Programs',
                'db_table': 'AlumniPrograms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('awardid', models.AutoField(db_column='AwardID', primary_key=True, serialize=False)),
                ('awardname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AwardName', max_length=100, null=True)),
                ('awardyear', models.IntegerField(blank=True, db_column='AwardYear', null=True)),
            ],
            options={
                'verbose_name_plural': 'Awards',
                'db_table': 'Awards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collaborationactivities',
            fields=[
                ('collaborationid', models.AutoField(db_column='CollaborationID', primary_key=True, serialize=False)),
                ('activityname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ActivityName', max_length=100, null=True)),
                ('activitydate', models.DateField(blank=True, db_column='ActivityDate', null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
            ],
            options={
                'db_table': 'CollaborationActivities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donationid', models.AutoField(db_column='DonationID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('donationdate', models.DateField(blank=True, db_column='DonationDate', null=True)),
            ],
            options={
                'verbose_name_plural': 'Donations',
                'db_table': 'Donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventparticipation',
            fields=[
                ('participationid', models.AutoField(db_column='ParticipationID', primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Role', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Participation',
                'db_table': 'EventParticipation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.AutoField(db_column='EventID', primary_key=True, serialize=False)),
                ('eventname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EventName', max_length=100, null=True)),
                ('eventtype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EventType', max_length=50, null=True)),
                ('eventdate', models.DateField(blank=True, db_column='EventDate', null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Externalinstitutions',
            fields=[
                ('institutionid', models.AutoField(db_column='InstitutionID', primary_key=True, serialize=False)),
                ('institutionname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='InstitutionName', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Country', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=50, null=True)),
                ('institutiontype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='InstitutionType', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ExternalInstitutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programparticipation',
            fields=[
                ('participationid', models.AutoField(db_column='ParticipationID', primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Role', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ProgramParticipation',
                'managed': False,
            },
        ),
    ]
