# Generated by Django 4.2.29 on 2026-03-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnidetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='alumniprograms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='collaborationactivities',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='donations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='externalinstitutions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='programparticipation',
            options={'managed': True},
        ),
    ]
