# Generated by Django 4.2.29 on 2026-03-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0002_alter_alumnidetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnidetails',
            name='isverified',
            field=models.BooleanField(db_column='IsVerified', default=False),
        ),
        migrations.AddField(
            model_name='alumnidetails',
            name='registration_number',
            field=models.CharField(blank=True, db_column='RegistrationNumber', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='alumniid',
            field=models.ForeignKey(blank=True, db_column='AlumniID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.alumnidetails'),
        ),
        migrations.AddField(
            model_name='collaborationactivities',
            name='institutionid',
            field=models.ForeignKey(blank=True, db_column='InstitutionID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.externalinstitutions'),
        ),
        migrations.AddField(
            model_name='donations',
            name='alumniid',
            field=models.ForeignKey(blank=True, db_column='AlumniID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.alumnidetails'),
        ),
        migrations.AddField(
            model_name='donations',
            name='eventid',
            field=models.ForeignKey(blank=True, db_column='EventID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.events'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='alumniid',
            field=models.ForeignKey(blank=True, db_column='AlumniID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.alumnidetails'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='eventid',
            field=models.ForeignKey(blank=True, db_column='EventID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.events'),
        ),
        migrations.AddField(
            model_name='programparticipation',
            name='alumniid',
            field=models.ForeignKey(blank=True, db_column='AlumniID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.alumnidetails'),
        ),
        migrations.AddField(
            model_name='programparticipation',
            name='programid',
            field=models.ForeignKey(blank=True, db_column='ProgramID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni_app.alumniprograms'),
        ),
    ]
