# Generated by Django 4.2.7 on 2026-03-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0002_alumniprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnidetails',
            options={'managed': True, 'verbose_name_plural': 'Alumni Details'},
        ),
        migrations.AlterModelOptions(
            name='alumniprograms',
            options={'managed': True, 'verbose_name_plural': 'Alumni Programs'},
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'managed': True, 'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='collaborationactivities',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='donations',
            options={'managed': True, 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'managed': True, 'verbose_name_plural': 'Event Participation'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True, 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='externalinstitutions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='programparticipation',
            options={'managed': True},
        ),
    ]
